# Generated by Django 5.0.7 on 2024-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Report')),
                ('is_check', models.BooleanField(default=False, verbose_name='Checked')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
