# Generated by Django 5.0.7 on 2024-11-27 10:42

import django.core.validators
import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('physique|profession|disease|fear|hobby|inventory')])),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
